skip_tags: true

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

os: Visual Studio 2015

services:
  - postgresql96

environment:
  COVERALLS_REPO_TOKEN:
    secure: W4++xmF7Q6ientAUP2crOR/1HDfmqanOk2NycHPjNVnCE7oS33FL4TwPJZEZw8Lc
  PGINSTALLATION: C:\Program Files\PostgreSQL\9.6\bin
  PGUSER: postgres
  PGPASSWORD: Password12!

  matrix:
    - PYTHON: C:\Python36
    - PYTHON: C:\Python36-x64

build_script:
  - PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%
  - createdb parsec_test_gw0
  - createdb parsec_test_gw1
  - which pg_config
  - pg_config --version
  - choco install winfsp -y --version=1.3.18160
  - git --no-pager log -n2
  - echo %APPVEYOR_REPO_COMMIT%
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;;%PATH%
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - pip install -U coveralls
  - pip install .[core,backend,dev]

test_script:
  # Uncomment this for RDP debug
  # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - py.test tests/ -n 2 --cov=parsec --cov-config=setup.cfg --runslow -x --postgresql

# TODO: re-enable me !
# on_success:
#   - coveralls
