skip_tags: true

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

os: Visual Studio 2015

services:
  - postgresql96

environment:
  PGINSTALLATION: C:\Program Files\PostgreSQL\9.6\bin

  matrix:
    # Disable 32 bits tests for the moment
    # - PYTHON: C:\Python36
    - PYTHON: C:\Python36-x64

build_script:
  - PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%
  - which pg_config
  - pg_config --version
  - choco install winfsp -y --version=1.4.19049
  - git --no-pager log -n2
  - echo %APPVEYOR_REPO_COMMIT%
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;;%PATH%
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - pip install -U wheel
  - python setup.py bdist_wheel
  # TODO: insert a sarcastic comment about lacking wildcard support, powershell
  # treating stderr output as error, impossibility to set variable from command
  # output and how unjustified windows crazinesses waste my time in general
  - python -c "import os, glob; cmd = 'pip install {}[core,backend,dev]'.format(glob.glob('dist/parsec_cloud-*.whl')[0]); print(cmd); raise SystemExit(os.system(cmd))"

test_script:
  # Uncomment this for RDP debug
  # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - mkdir empty
  - cd empty
  # No sed ? Hold my beer !
  - python -c "from pathlib import Path; fd = Path('../setup.cfg'); fd.write_text(fd.read_text().replace('parsec/core/gui/*', 'parsec/core/gui/*,../parsec/core/gui/*'))"
  - py.test ../tests/ --cov=parsec --cov-config=../setup.cfg --rungui --log-level=DEBUG -vvv -x
  - py.test ../tests/ -n 2 --max-worker-restart=0 --cov=parsec --cov-config=../setup.cfg --runmountpoint --runslow -x --postgresql --log-level=DEBUG -vvv -x

on_success:
  - pip install -U --user codecov
  - python -m codecov
