skip_tags: true

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

os: Visual Studio 2015

services:
  - postgresql96

environment:
  COVERALLS_REPO_TOKEN:
    secure: W4++xmF7Q6ientAUP2crOR/1HDfmqanOk2NycHPjNVnCE7oS33FL4TwPJZEZw8Lc
  PGINSTALLATION: C:\Program Files\PostgreSQL\9.6\bin

  matrix:
    # Disable 32 bits tests for the moment
    # - PYTHON: C:\Python36
    - PYTHON: C:\Python36-x64

build_script:
  - PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%
  - which pg_config
  - pg_config --version
  - choco install winfsp -y --version=1.4.19016
  - git --no-pager log -n2
  - echo %APPVEYOR_REPO_COMMIT%
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;;%PATH%
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - pip install -U coveralls wheel
  - python setup.py bdist_wheel
  - ps: pip install (ls dist/parsec_cloud-*.whl)[core,backend,dev]

test_script:
  # Uncomment this for RDP debug
  # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - mkdir empty
  - cd empty
  - py.test ../tests/ -n 2 --cov=parsec --cov-config=../setup.cfg --runslow --runmountpoint -x --postgresql --log-level=DEBUG -vvv

# TODO: re-enable me !
# on_success:
#   - coveralls
