repos:
# TODO: Enable this once we are confident Isort&Black end-up in a formatting deadlock
# -   repo: https://github.com/pre-commit/mirrors-isort
#     rev: v4.3.21
#     hooks:
#     -   id: isort
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      args:
          - "--line-length=100"
          - "--exclude=parsec/core/gui/_resources_rc.py"
          - "--exclude=parsec/core/gui/ui/"
      language_version: python3
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: mixed-line-ending
      args:
        - "--fix=lf"
    - id: trailing-whitespace
