language: python
cache:
  directories:
  - $HOME/ossl-1/
matrix:
    include:
        - python: 3.4
          env: OPENSSL=1.1.0c
        - python: 3.5
          env: OPENSSL=1.1.0c
install:
- bash ./.travis/install.sh
- pip install -U coveralls
- pip install -Ur requirements_dev.txt
script:
- bash ./.travis/run.sh
after_success:
- coveralls
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: touilleMan
  password:
    secure: Kymr6A/qQ3+rvyzn1Yts9YEpBKCQtl9JyDF7xj/XRLh6VmnY9ocamkBCAL/fALGl5qWwBjEWqYOVhlHmR5cC1evSs8FqgG4OJItp5fVm1cNdniYwwTQ19DE7m/kJbzDouIrCpmSwb48TlHSU1IhbH1Nsbmz3Qz2mysVlk7PswGJ9Q9kfy4HoMy+9c9PKMFdFbSNdmXTSAUTJgVVLR4StxE2HcApVOUDN8S9GAQJB7ZQLjZhKHseoUMleazQrsZcHCcv6UKGvj/mC5Vloh7v/evUBkRpeOPhRRgPRc/SaF8VyII7PqYeqFS7swxTghTSCLAnN/DCWF5iXaNGLC59g9VQ6CYhB8TZlZ/wRXp6qOJLXP4vQ9F6HwT5s8YBtxUn/rJn2q4tE2vfvJKVeYQ04KFBkLXQsFRgkalkDjrx+mzNrAlPeXvLuKyg44u/s1F1mPdiE5FgBRDGCEh3ompydro2yZNtGcQyhN9tOasdH42q1rYd4W24Ty9tn66L9Okosw6bu2t+QP5LG4tRLms33qec39aPz5KxJ5AYNekRyyb1pCpR484hjp6ATYer7CKvGnZAxxQInAMfezCzcMwme2FsdlWaPXBtBVWWevGFj+fnEItNuBLzWOeaHBDPZKLFjs7QcU3Gm7bTqLxL/Hs6yOjOJ1UZRXDCl8MkkHa4Kl8Q=
  on:
    tags: true
    repo: Scille/parsec-cloud
    condition: $TRAVIS_PYTHON_VERSION == 3.5
