sudo: required
language: python
python:
- '3.6'
#- '3.7-dev'

addons:
  apt:
    packages:
    - postgresql-10
    - postgresql-server-dev-10
    - desktop-file-utils

env:
  global:
  - PGINSTALLATION=/usr/lib/postgresql/10/bin

install:
# Update packaging packages
- pip install -U wheel pip setuptools twine
# Install code quality check tools
- pip install flake8==3.7.7 black==19.3b0
# Workaround a compatibility issue by pre-installing requests
- pip install requests
# Build the parsec wheel
- python setup.py bdist_wheel
# Make sure the python package is ready for release
- twine check dist/parsec_cloud-*.whl
# Install the parsec wheel with all dependencies
- pip install $(ls dist/parsec_cloud-*.whl)[all]
# Check dependency compatibility
- pip check parsec[all]

before_script:
- sudo modprobe fuse

script:
- set -e  # stop build as soon as a command fails
- git fetch --tags  # Needed by releaser.py to have a consistent `git describe`
- python ./misc/releaser.py check --verbose
# Only print output if check failed
- OUT=$(2>&1 ./misc/autoformat.sh --check) || (echo $OUT; $(exit 1))
- flake8 setup.py parsec tests
- python ./misc/license_headers.py check
- mkdir empty && cd empty
- sed -i 's#omit = \(.*\)#omit = \1,../\1#' ../setup.cfg  # fix path
# Run everything with memory driver
- py.test ../tests/ --runmountpoint --runslow -n 2 --max-worker-restart=0  --log-level=DEBUG -vvv -x --cov=parsec --cov-config=../setup.cfg --cov-append
# Run backend tests with postgresql driver
- py.test ../tests/backend ../tests/test_cli.py --postgresql --runslow -n 2 --max-worker-restart=0  --log-level=DEBUG -vvv -x --cov=parsec --cov-config=../setup.cfg --cov-append
# The GUI tests fail on travis for some reason, even with the xvfb service
# - py.test ../tests/ -m gui --runmountpoint --runslow --rungui -vvv -x --log-level=DEBUG --cov=parsec --cov-config=../setup.cfg --cov-append
- set +e

after_success:
- pip install -U codecov
- codecov

before_deploy:
- cd $TRAVIS_BUILD_DIR

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: ZNE4R2wtpK1/PksXqusYLpyuYC7vIOtcJJEtn+hGI8+bseYoT404eFHJjFJSDt0bjS4lv6tWfZcSwneM5KlWGmkHgQTKquf11FY7gtANoUHVS0PZK/3byyZ1x58p4k9hiR6vocAXgRejrKARCfzgkLfow7bgyAXGCTSFWwbe7rSuqgI8Froij1TOv3z1iuq7TfqfwpNs2A0odJO2xnY7qZYrHHT3KZbZ/YzRgQZCAAzAlDMdhDk15qF50ib2OhO4B6a929ZxDpYpkDfW1bZS6j45WkXXR4fJLjzJnSTnSVCG3F1UhFATvkxhSJTO2hKhZ0al1UnhtGLoXSLj1P1b/Oyf14K9O4BA6Wu6vD+tMy1ua1nkgghk1DzNaS/B6QR6wZadT/jkl7Xzpd/RSX3Q3fMrYtSSnStgnszd5X6bGx4cZJg/k2XQ0I3tHdkub+vcMDl6uz9Q+Z/po+L6va4K2xlt6V5cQhKJgZ7gnzDd0UXtYSXyHyfUKbHyfXjQY9heCA8WXR8H60zR7i5FZYjOAczz7i5Dw3g/THAaDFhXKS2CoQILMIyKKWSPAQoGr2If6GA38vRTa+/GaUaanZJy8BVlK6YJO1RVlU4oF12vgYeQ1y/B71OYql/Rw8hqm+u/6KS1pAcP+pZPhqwqgt0+nOW/hB866zWtWkfhcyqjhZg=
  on:
    tags: true
    repo: Scille/parsec-cloud
    python: 3.6
