sudo: required
language: python
python:
- '3.6'
#- '3.7-dev'
services:
  - postgresql
addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-server-dev-9.5
install:
- pip install -U coveralls
- pip install .[all]
before_script:
  - sudo modprobe fuse
script:
# Only print output if check failed
- OUT=$(2>&1 ./misc/autoformat.sh --check) || (echo $OUT; $(exit 1))
- flake8
- ./misc/license_headers.py check
- py.test tests -n 2 --cov=parsec --cov-config=setup.cfg --log-level=DEBUG -vvv
- py.test tests -n 2 --cov=parsec --cov-config=setup.cfg --runslow --runfuse --postgresql --log-level=DEBUG -vvv
after_success:
- coveralls
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: touilleMan
  password:
    secure: Kymr6A/qQ3+rvyzn1Yts9YEpBKCQtl9JyDF7xj/XRLh6VmnY9ocamkBCAL/fALGl5qWwBjEWqYOVhlHmR5cC1evSs8FqgG4OJItp5fVm1cNdniYwwTQ19DE7m/kJbzDouIrCpmSwb48TlHSU1IhbH1Nsbmz3Qz2mysVlk7PswGJ9Q9kfy4HoMy+9c9PKMFdFbSNdmXTSAUTJgVVLR4StxE2HcApVOUDN8S9GAQJB7ZQLjZhKHseoUMleazQrsZcHCcv6UKGvj/mC5Vloh7v/evUBkRpeOPhRRgPRc/SaF8VyII7PqYeqFS7swxTghTSCLAnN/DCWF5iXaNGLC59g9VQ6CYhB8TZlZ/wRXp6qOJLXP4vQ9F6HwT5s8YBtxUn/rJn2q4tE2vfvJKVeYQ04KFBkLXQsFRgkalkDjrx+mzNrAlPeXvLuKyg44u/s1F1mPdiE5FgBRDGCEh3ompydro2yZNtGcQyhN9tOasdH42q1rYd4W24Ty9tn66L9Okosw6bu2t+QP5LG4tRLms33qec39aPz5KxJ5AYNekRyyb1pCpR484hjp6ATYer7CKvGnZAxxQInAMfezCzcMwme2FsdlWaPXBtBVWWevGFj+fnEItNuBLzWOeaHBDPZKLFjs7QcU3Gm7bTqLxL/Hs6yOjOJ1UZRXDCl8MkkHa4Kl8Q=
  on:
    tags: true
    repo: Scille/parsec-cloud
    python: 3.6
