version: '3'
services:
  backend:
    image: parsec
    ports:
      - "6777:6777"
  core:
    image: parsec
    ports:
      - "6776:6776"
    depends_on:
      - backend
    command: core --I-am-John --backend-addr=tcp://backend:6777
